version: '3'
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app
    env_file:
    - .env
    command: npm run start:dev
    ports:
      - 3000:3000
